# Introduccion a la libreria Numpy

In [1]:
import numpy as np

In [5]:
# Creamos una matriz de numeros que conocemos para poder trabajar con ellos
valoraciones = np.array([[[8, 7, 8, 5], [2, 5, 5, 2]], [[2, 6, 8, 4], [8, 9, 7, 4]], [[8, 8, 9, 3], [10, 9, 10, 8]]])
valoraciones

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [6]:
# Obtener un valor dentro del arreglo que estamos mostrando 
#           conjunto
#               fila
#                   columna
valoraciones[0, 1, 2]

5

In [8]:
# Crear arreglos de Zeros
np.zeros((3, 2, 4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [10]:
# Prueba
np.zeros((10, 10, 10, 10))

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
    

In [13]:
# Operaciones con Arreglos del mismo tamaño

# Sumarle a las valoraciones un valor e imprimirlo
valoraciones + np.ones((3, 2, 4), dtype = int)

array([[[ 9,  8,  9,  6],
        [ 3,  6,  6,  3]],

       [[ 3,  7,  9,  5],
        [ 9, 10,  8,  5]],

       [[ 9,  9, 10,  4],
        [11, 10, 11,  9]]])

In [14]:
# Comprobacion del valor del arreglo original

valoraciones

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [16]:
# Calcular la media de las valoraciones
np.mean(valoraciones)

6.458333333333333

In [18]:
# Calcular la media de las valoraciones de un eje en especifico mediante axis
np.mean(valoraciones, axis = 0)

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.33333333, 4.66666667]])

In [19]:
np.mean(valoraciones, axis=1)

array([[5. , 6. , 6.5, 3.5],
       [5. , 7.5, 7.5, 4. ],
       [9. , 8.5, 9.5, 5.5]])

In [20]:
np.mean(valoraciones, axis=2)

array([[7.  , 3.5 ],
       [5.  , 7.  ],
       [7.  , 9.25]])

In [22]:
# Reacomodar los valores de un arreglo
np.reshape([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], (3, 2, 2))
# Debe ser coherente que los valores de la matriz se adapten a los valores que deseamos transformar

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [24]:
# Generar objetos random
np.random.rand(2, 2)

array([[0.88848992, 0.54901327],
       [0.03733681, 0.17341401]])